#!/bin/bash
##################################################################
## Server for Centos
##################################################################

##################################################################
## 1. Mysql
##################################################################
# CentOS 7.0+ 不支持 mysql 换成了 mariadb
yum install mariadb-server mariadb 
mysqladmin -u root password "root"  # 修改密码
# mariadb 操作
systemctl start mariadb  #启动MariaDB
systemctl stop mariadb  #停止MariaDB
systemctl restart mariadb  #重启MariaDB
systemctl enable mariadb  #设置开机启动
# 先启动数据库, 密码默认为空, 如果启动 mariadb, 输入 mysql -u root -p 会提示:
# Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'
systemctl start mariadb  #启动MariaDB
mysql -u root -p  # 密码默认为空, 提示符也换成了 mariadb
# /etc/my.cnf 是配置文件

##################################################################
## 2. php
##################################################################
yum install php php-mysql php-fpm
# 解决 php 安全威胁
vi /etc/php.ini
```cgi.fix_pathinfo=0```
# 如此PHP的只會處理確切位置的檔案，一來加快速度二來更安全，修改完後重新啟動PHP：
# 配置 php-fpm
vi /etc/php-fpm.d/www.conf
```
listen = /var/run/php-fpm/php-fpm.sock
listen.owner = nobody
listen.group = nobody
user = nginx
group = nginx
```
service php-fpm stop
service php-fpm start
chkconfig php-fpm on

##################################################################
## 3. Nginx 和 2. PHP 一块配置
##################################################################
yum install epel-release
yum install nginx
# 设置开机启动
service httpd stop
chkconfig httpd off
service nginx start
chkconfig nginx on
# 配置 nginx 解析 php
vi /etc/nginx/conf.d/default.conf  # 或者
vim /etc/nginx/nginx.conf
```
# 大概是这样的, 注意 php 那段
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;
    root         /usr/share/nginx/html;
    index index.php index.html index.htm;

    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    location / {
    }
    location ~ \.php$ {
	#    root           html;
	    try_files $uri =404;
	    fastcgi_pass  unix:/var/run/php-fpm/php-fpm.sock; 
	    fastcgi_index  index.php;
	    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
	    include        fastcgi_params;
	}
    error_page 404 /404.html;
        location = /40x.html {
    }
    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}
```
# 重启
service nginx reload
# 关闭
nginx -s stop
nginx -s qiut
service nginx stop

##################################################################
## 4. xampp
##################################################################
chmod 777 xampp.run && ./xampp.run
sudo /opt/lampp/lampp stop/start/restart
sudo /opt/lampp/lampp startapache  # 至启动单个的,其它一次类推
sudo /opt/lampp/lampp security  # 为各种软件设置密码 root root
http://115.28.247.19/phpmyadmin/  # phpmyadmin username: xampp passwd: root
/opt/lampp/htdocs/  # 网站根目录
/opt/lampp/etc/httpd.conf  # apache 配置文件
/opt/lampp/etc/my.cnf  # mysql 配置文件
/opt/lampp/etc/php.ini  # php 配置文件
/opt/lampp/etc/proftpd.conf  # proftpd 配置文件
/opt/lampp/phpmyadmin/config.inc.php  # phpmyadmin 配置文件
# 卸载
sudo /opt/lampp/lampp stop
sudo rm -rf /opt/lampp

##################################################################
## 5. DVWA
##################################################################
# 解压到网站根目录下
/opt/lampp/htdocs/DVWA/config/config.inc.php  # 配置文件
# 修改其中的 mysql 密码
# 进入网站, reset -> username: admin; passwd: passwd
# 正常情况下,可以在 mysql中看到五个users
